# Generated by Django 3.1.5 on 2021-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='company',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
