# Generated by Django 3.1.5 on 2021-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_adv_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adv',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
